version: "3"
services:
  codesender.api:
    build: .      
    image: hubdocker.azurecr.io/codesender/api:latest
    ports: 
      - "60000:80"
    depends_on:
      - db
    links:
      - db
    tty: true
  db:
    image: hubdocker.azurecr.io/codesender/database:latest
    ports:
      - "1433:1433"
    expose: 
      - "1433"
    environment:
      SA_PASSWORD: "Secret1234"
      ACCEPT_EULA: "Y"      